Repository ManageIQ/kubevirt-sdk-ruby, pull requests merged in 2025-02, with the labels that each got.

#3 Add License
  LICENSE.txt
Labels: documentation

#7 Inherit renovate config from a central location
  renovate.json
Labels: developer

#8 Replace Travis-CI with GitHub Actions
  .github/workflows/ci.yaml
  .gitlab-ci.yml
  .travis.yml
Labels: test
